
# unbind C-b
set -s escape-time 0
# set-option -g prefix C-a

set-option -g default-terminal "screen-256color"

# set -g default-terminal "alacritty"
# set-option -sa terminal-overrides ",alacritty*:Tc"

set -g default-terminal "tmux-256color"
set -g terminal-features ",alacritty:RGB"

set -g status-style "fg=#454545"
set -g status-bg default
set -g status-position top
set -g status-interval 1
set -g status-left "[#S] "
set -g status-right ""
setw -g mode-keys vi

set -g detach-on-destroy off
# set -g base-index 1

# vim-like pane switching
bind -r ^ last-window
bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R

# bind Space copy-mode

set -g message-style "bg=#4e4e4e"
# set -g mode-style "bg=#f0e68c,fg=black"
# set -g mode-style "bg=#816382,fg=white"
# set -g mode-style "bg=#81a355,fg=black"
set -g mode-style "bg=#b8b8b8,fg=black"


bind -T copy-mode-vi 'y' send -X copy-selection-and-cancel
bind -T copy-mode-vi 'v' send -X begin-selection

# forget the find window.  That is for chumps
bind-key -r f run-shell "tmux neww ~/.local/bin/tmux-sessionizer"

bind-key -T root C-c if -F "#{==:#{pane_mode},tree-mode}" \
  "send-keys q" \
  "send-keys C-c"
